set termencoding=utf8
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set mousehide
set mouse=a
set ruler
set hlsearch
syntax on
set background=dark
colorscheme OceanicNext
